# Generated by Django 2.0 on 2017-12-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=255)),
                ('agency_url', models.CharField(max_length=512)),
                ('agency_timezone', models.CharField(max_length=255)),
                ('agency_phone', models.CharField(max_length=255)),
                ('agency_lang', models.CharField(max_length=255)),
            ],
        ),
    ]
